import { CYCLE_PHASE_DESCRIPTIONS } from '@/features/hormoneBalance/hormoneCalculations'
import type { CyclePhaseEstimate } from '@/features/hormoneBalance/hormoneCalculations'
import type { EnergyTrendResult, MoodTrendResult, WeeklyCheckInSummary } from '@/features/insights/types'

const NOT_MEDICAL_ADVICE = 'This is not medical advice.'

export interface HormoneInsight {
  id: string
  title: string
  message: string
}

export interface GenerateHormoneInsightsInput {
  weeklySummary: WeeklyCheckInSummary
  moodTrend: MoodTrendResult
  energyTrend: EnergyTrendResult
  cyclePhaseEstimate: CyclePhaseEstimate | null
}

/**
 * Rule-based, deterministic insight generator — the same honest pattern
 * used across HerHealth (Wellness Insights, Fertility Journey, Baby
 * Growth). Every message describes only the user's own recorded
 * check-ins/period dates; nothing here is generated by a model, and every
 * insight says so plainly.
 */
export function generateHormoneInsights(input: GenerateHormoneInsightsInput): HormoneInsight[] {
  const { weeklySummary, moodTrend, energyTrend, cyclePhaseEstimate } = input
  const insights: HormoneInsight[] = []

  if (energyTrend === 'Improving') {
    insights.push({
      id: 'energy-improving',
      title: 'Energy pattern',
      message: `Your recorded check-ins suggest your energy has been trending upward, especially on days following more consistent check-ins. ${NOT_MEDICAL_ADVICE}`,
    })
  } else if (energyTrend === 'Decreasing') {
    insights.push({
      id: 'energy-decreasing',
      title: 'Energy pattern',
      message: `Your recorded check-ins show lower energy recently. Sleep, stress, and cycle phase can all influence how energy feels day to day. ${NOT_MEDICAL_ADVICE}`,
    })
  }

  if (moodTrend === 'Mixed' || energyTrend === 'Mixed') {
    insights.push({
      id: 'mood-energy-mixed',
      title: 'Mood and energy patterns',
      message: `Your recent entries show some variation in mood and energy. Everyday factors like stress, sleep, and routine changes may influence this. ${NOT_MEDICAL_ADVICE}`,
    })
  }

  if (weeklySummary.count > 0 && weeklySummary.consistencyPercent >= 70) {
    insights.push({
      id: 'tracking-consistency',
      title: 'Wellness habits',
      message: `You've checked in on ${weeklySummary.consistencyPercent}% of the last 7 days — consistent tracking like this builds a clearer picture of your own patterns over time. ${NOT_MEDICAL_ADVICE}`,
    })
  }

  if (cyclePhaseEstimate) {
    insights.push({
      id: 'cycle-phase',
      title: 'Cycle phase (estimated)',
      message: `Based on the period dates you've recorded, you're likely in your ${cyclePhaseEstimate.phase.toLowerCase()} phase. During this phase, ${CYCLE_PHASE_DESCRIPTIONS[cyclePhaseEstimate.phase]}. ${NOT_MEDICAL_ADVICE}`,
    })
  }

  if (insights.length === 0) {
    insights.push({
      id: 'getting-started',
      title: 'Getting started',
      message: `Keep recording daily check-ins and period dates, and HerHealth will surface gentle observations about your own patterns here. ${NOT_MEDICAL_ADVICE}`,
    })
  }

  return insights
}

export interface HormoneSuggestion {
  id: string
  message: string
}

/**
 * Gentle, non-diagnostic wellness suggestions. Never mentions a condition
 * or disease, and never claims to predict or treat anything — only ever
 * general, supportive lifestyle nudges, lightly informed by the user's own
 * recent trend where one exists.
 */
export function generateHormoneSuggestions(input: {
  moodTrend: MoodTrendResult
  energyTrend: EnergyTrendResult
}): HormoneSuggestion[] {
  const suggestions: HormoneSuggestion[] = []

  if (input.energyTrend === 'Decreasing') {
    suggestions.push({
      id: 'rest',
      message: 'Consider giving yourself some extra rest today — your recent entries suggest lower energy.',
    })
  }

  if (input.moodTrend === 'Mixed') {
    suggestions.push({
      id: 'gentle-reflection',
      message: 'A few quiet minutes of reflection or journaling can help make sense of a shifting mood.',
    })
  }

  suggestions.push(
    { id: 'sleep', message: 'Prioritize consistent sleep and wake times where you can.' },
    { id: 'hydration', message: 'Stay hydrated throughout the day.' },
    { id: 'stress', message: 'Practice a short stress-reduction moment, like slow breathing or gentle stretching.' },
    { id: 'movement', message: 'Take a short walk or another gentle movement break.' },
    { id: 'nutrition', message: 'Aim for balanced, regular meals when it works for you.' },
  )

  return suggestions
}
